// Package dbtemplates provides one-click database projects. A template is
// nothing proprietary: it generates an ordinary compose project plus
// encrypted env vars — exactly what a user would write by hand (principle 4).
package dbtemplates

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
)

type Template struct {
	Key         string `json:"key"`
	Name        string `json:"name"`
	Description string `json:"description"`
	// DefaultPort is the host port the database publishes on 127.0.0.1.
	DefaultPort int `json:"default_port"`
}

var All = []Template{
	{Key: "postgres", Name: "PostgreSQL 17", Description: "Relational database, published on 127.0.0.1:5432", DefaultPort: 5432},
	{Key: "redis", Name: "Redis 7", Description: "In-memory data store, published on 127.0.0.1:6379", DefaultPort: 6379},
	{Key: "mysql", Name: "MySQL 8.4", Description: "Relational database, published on 127.0.0.1:3306", DefaultPort: 3306},
	{Key: "mongodb", Name: "MongoDB 8", Description: "Document database, published on 127.0.0.1:27017", DefaultPort: 27017},
}

func Get(key string) (Template, bool) {
	for _, t := range All {
		if t.Key == key {
			return t, true
		}
	}
	return Template{}, false
}

// Render returns the compose file and env vars for a template instance.
// Credentials are generated fresh per instance and stored encrypted.
func Render(key, project string, hostPort int) (compose string, env map[string]string, err error) {
	t, ok := Get(key)
	if !ok {
		return "", nil, fmt.Errorf("unknown template %q", key)
	}
	if hostPort <= 0 {
		hostPort = t.DefaultPort
	}
	password, err := randomSecret()
	if err != nil {
		return "", nil, err
	}

	header := "# Generated by Windlass from the " + t.Name + " template.\n" +
		"# This is a plain compose project — edit it like any other.\n"

	switch key {
	case "postgres":
		return header + fmt.Sprintf(`services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:%d:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 12
volumes:
  postgres_data:
`, hostPort), map[string]string{
				"POSTGRES_USER":     "windlass",
				"POSTGRES_PASSWORD": password,
				"POSTGRES_DB":       project,
			}, nil

	case "redis":
		return header + fmt.Sprintf(`services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "127.0.0.1:%d:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 12
volumes:
  redis_data:
`, hostPort), map[string]string{
				"REDIS_PASSWORD": password,
			}, nil

	case "mysql":
		return header + fmt.Sprintf(`services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "127.0.0.1:%d:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 20
volumes:
  mysql_data:
`, hostPort), map[string]string{
				"MYSQL_ROOT_PASSWORD": password,
				"MYSQL_USER":          "windlass",
				"MYSQL_PASSWORD":      password,
				"MYSQL_DATABASE":      project,
			}, nil

	case "mongodb":
		return header + fmt.Sprintf(`services:
  mongodb:
    image: mongo:8
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "127.0.0.1:%d:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ping:1}).ok' | grep 1"]
      interval: 5s
      timeout: 3s
      retries: 12
volumes:
  mongo_data:
`, hostPort), map[string]string{
				"MONGO_USER":     "windlass",
				"MONGO_PASSWORD": password,
			}, nil
	}
	return "", nil, fmt.Errorf("unknown template %q", key)
}

func randomSecret() (string, error) {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}
