// Package store owns the SQLite database: opening it with the right
// pragmas and applying embedded migrations. Queries are generated by sqlc.
package store

import (
	"database/sql"
	"fmt"
	"net/url"

	_ "modernc.org/sqlite" // pure-Go driver: CGO-free cross-compilation
)

// Open opens (creating if needed) the SQLite database at path with WAL mode,
// foreign keys, and a busy timeout. A single connection is used: Windlass is
// a metadata store with light write traffic, and one writer sidesteps
// SQLITE_BUSY entirely.
func Open(path string) (*sql.DB, error) {
	dsn := fmt.Sprintf("file:%s?%s", url.PathEscape(path), url.Values{
		"_pragma": []string{
			"journal_mode(WAL)",
			"foreign_keys(ON)",
			"busy_timeout(5000)",
			"synchronous(NORMAL)",
		},
	}.Encode())

	db, err := sql.Open("sqlite", dsn)
	if err != nil {
		return nil, fmt.Errorf("open sqlite: %w", err)
	}
	db.SetMaxOpenConns(1)

	if err := db.Ping(); err != nil {
		db.Close()
		return nil, fmt.Errorf("ping sqlite: %w", err)
	}
	return db, nil
}
