// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"
	"database/sql"
)

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_log (user_id, action, resource_type, resource_id, ip, detail)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAuditParams struct {
	UserID       sql.NullInt64
	Action       string
	ResourceType sql.NullString
	ResourceID   sql.NullString
	Ip           sql.NullString
	Detail       sql.NullString
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertAudit,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Ip,
		arg.Detail,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT id, ts, user_id, "action", resource_type, resource_id, ip, detail FROM audit_log ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListAuditParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAudit, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Ip,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
