// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: backups.sql

package db

import (
	"context"
	"database/sql"
)

const createBackup = `-- name: CreateBackup :one
INSERT INTO backups (project_id, kind, destination) VALUES (?, ?, ?)
RETURNING id, project_id, kind, destination, path, size, status, error, created_at, finished_at
`

type CreateBackupParams struct {
	ProjectID   int64
	Kind        string
	Destination string
}

func (q *Queries) CreateBackup(ctx context.Context, arg CreateBackupParams) (Backup, error) {
	row := q.db.QueryRowContext(ctx, createBackup, arg.ProjectID, arg.Kind, arg.Destination)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Destination,
		&i.Path,
		&i.Size,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteBackup = `-- name: DeleteBackup :exec
DELETE FROM backups WHERE id = ?
`

func (q *Queries) DeleteBackup(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBackup, id)
	return err
}

const finishBackup = `-- name: FinishBackup :exec
UPDATE backups
SET status = ?, path = ?, size = ?, error = ?,
    finished_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type FinishBackupParams struct {
	Status string
	Path   string
	Size   int64
	Error  sql.NullString
	ID     int64
}

func (q *Queries) FinishBackup(ctx context.Context, arg FinishBackupParams) error {
	_, err := q.db.ExecContext(ctx, finishBackup,
		arg.Status,
		arg.Path,
		arg.Size,
		arg.Error,
		arg.ID,
	)
	return err
}

const getBackup = `-- name: GetBackup :one
SELECT b.id, b.project_id, b.kind, b.destination, b.path, b.size, b.status, b.error, b.created_at, b.finished_at FROM backups b
JOIN projects p ON p.id = b.project_id
WHERE p.name = ? AND b.id = ?
`

type GetBackupParams struct {
	Name string
	ID   int64
}

func (q *Queries) GetBackup(ctx context.Context, arg GetBackupParams) (Backup, error) {
	row := q.db.QueryRowContext(ctx, getBackup, arg.Name, arg.ID)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Destination,
		&i.Path,
		&i.Size,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getBackupSchedule = `-- name: GetBackupSchedule :one
SELECT id, project_id, interval, destination, retention_count, enabled, last_run_at FROM backup_schedules WHERE project_id = ?
`

func (q *Queries) GetBackupSchedule(ctx context.Context, projectID int64) (BackupSchedule, error) {
	row := q.db.QueryRowContext(ctx, getBackupSchedule, projectID)
	var i BackupSchedule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Interval,
		&i.Destination,
		&i.RetentionCount,
		&i.Enabled,
		&i.LastRunAt,
	)
	return i, err
}

const listBackupsForPrune = `-- name: ListBackupsForPrune :many
SELECT id, project_id, kind, destination, path, size, status, error, created_at, finished_at FROM backups
WHERE project_id = ? AND status = 'done' AND destination = 'local'
ORDER BY id DESC
`

func (q *Queries) ListBackupsForPrune(ctx context.Context, projectID int64) ([]Backup, error) {
	rows, err := q.db.QueryContext(ctx, listBackupsForPrune, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Backup
	for rows.Next() {
		var i Backup
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Destination,
			&i.Path,
			&i.Size,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueSchedules = `-- name: ListDueSchedules :many
SELECT s.id, s.project_id, s.interval, s.destination, s.retention_count, s.enabled, s.last_run_at, p.name AS project_name
FROM backup_schedules s
JOIN projects p ON p.id = s.project_id
WHERE s.enabled = 1
`

type ListDueSchedulesRow struct {
	ID             int64
	ProjectID      int64
	Interval       string
	Destination    string
	RetentionCount int64
	Enabled        int64
	LastRunAt      sql.NullString
	ProjectName    string
}

func (q *Queries) ListDueSchedules(ctx context.Context) ([]ListDueSchedulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDueSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueSchedulesRow
	for rows.Next() {
		var i ListDueSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Interval,
			&i.Destination,
			&i.RetentionCount,
			&i.Enabled,
			&i.LastRunAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectBackups = `-- name: ListProjectBackups :many
SELECT b.id, b.project_id, b.kind, b.destination, b.path, b.size, b.status, b.error, b.created_at, b.finished_at FROM backups b
JOIN projects p ON p.id = b.project_id
WHERE p.name = ?
ORDER BY b.id DESC
LIMIT 50
`

func (q *Queries) ListProjectBackups(ctx context.Context, name string) ([]Backup, error) {
	rows, err := q.db.QueryContext(ctx, listProjectBackups, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Backup
	for rows.Next() {
		var i Backup
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Destination,
			&i.Path,
			&i.Size,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchScheduleRun = `-- name: TouchScheduleRun :exec
UPDATE backup_schedules
SET last_run_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

func (q *Queries) TouchScheduleRun(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchScheduleRun, id)
	return err
}

const upsertBackupSchedule = `-- name: UpsertBackupSchedule :exec
INSERT INTO backup_schedules (project_id, interval, destination, retention_count, enabled)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(project_id) DO UPDATE SET
    interval = excluded.interval,
    destination = excluded.destination,
    retention_count = excluded.retention_count,
    enabled = excluded.enabled
`

type UpsertBackupScheduleParams struct {
	ProjectID      int64
	Interval       string
	Destination    string
	RetentionCount int64
	Enabled        int64
}

func (q *Queries) UpsertBackupSchedule(ctx context.Context, arg UpsertBackupScheduleParams) error {
	_, err := q.db.ExecContext(ctx, upsertBackupSchedule,
		arg.ProjectID,
		arg.Interval,
		arg.Destination,
		arg.RetentionCount,
		arg.Enabled,
	)
	return err
}
