// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployments.sql

package db

import (
	"context"
	"database/sql"
)

const countActiveDeployments = `-- name: CountActiveDeployments :one
SELECT COUNT(*) FROM deployments
WHERE project_id = ?
  AND status NOT IN ('succeeded', 'failed', 'cancelled')
`

func (q *Queries) CountActiveDeployments(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveDeployments, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (project_id, number, triggered_by, rollback_of)
VALUES (
    ?,
    (SELECT COALESCE(MAX(d2.number), 0) + 1 FROM deployments d2 WHERE d2.project_id = ?),
    ?,
    ?
)
RETURNING id, project_id, number, status, triggered_by, git_commit, error, rollback_of, started_at, finished_at, created_at
`

type CreateDeploymentParams struct {
	ProjectID   int64
	ProjectID_2 int64
	TriggeredBy string
	RollbackOf  sql.NullInt64
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, createDeployment,
		arg.ProjectID,
		arg.ProjectID_2,
		arg.TriggeredBy,
		arg.RollbackOf,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Status,
		&i.TriggeredBy,
		&i.GitCommit,
		&i.Error,
		&i.RollbackOf,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const finishDeployment = `-- name: FinishDeployment :exec
UPDATE deployments
SET status = ?, error = ?, finished_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type FinishDeploymentParams struct {
	Status string
	Error  sql.NullString
	ID     int64
}

func (q *Queries) FinishDeployment(ctx context.Context, arg FinishDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, finishDeployment, arg.Status, arg.Error, arg.ID)
	return err
}

const getDeployment = `-- name: GetDeployment :one
SELECT d.id, d.project_id, d.number, d.status, d.triggered_by, d.git_commit, d.error, d.rollback_of, d.started_at, d.finished_at, d.created_at FROM deployments d
JOIN projects p ON p.id = d.project_id
WHERE p.name = ? AND d.number = ?
`

type GetDeploymentParams struct {
	Name   string
	Number int64
}

func (q *Queries) GetDeployment(ctx context.Context, arg GetDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeployment, arg.Name, arg.Number)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Status,
		&i.TriggeredBy,
		&i.GitCommit,
		&i.Error,
		&i.RollbackOf,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeploymentByID = `-- name: GetDeploymentByID :one
SELECT id, project_id, number, status, triggered_by, git_commit, error, rollback_of, started_at, finished_at, created_at FROM deployments WHERE id = ?
`

func (q *Queries) GetDeploymentByID(ctx context.Context, id int64) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentByID, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Status,
		&i.TriggeredBy,
		&i.GitCommit,
		&i.Error,
		&i.RollbackOf,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertDeploymentArtifact = `-- name: InsertDeploymentArtifact :exec
INSERT INTO deployment_artifacts (deployment_id, service, image_ref, image_digest)
VALUES (?, ?, ?, ?)
ON CONFLICT(deployment_id, service) DO UPDATE
SET image_ref = excluded.image_ref, image_digest = excluded.image_digest
`

type InsertDeploymentArtifactParams struct {
	DeploymentID int64
	Service      string
	ImageRef     string
	ImageDigest  string
}

func (q *Queries) InsertDeploymentArtifact(ctx context.Context, arg InsertDeploymentArtifactParams) error {
	_, err := q.db.ExecContext(ctx, insertDeploymentArtifact,
		arg.DeploymentID,
		arg.Service,
		arg.ImageRef,
		arg.ImageDigest,
	)
	return err
}

const insertDeploymentEvent = `-- name: InsertDeploymentEvent :one
INSERT INTO deployment_events (deployment_id, seq, type, message)
VALUES (
    ?,
    (SELECT COALESCE(MAX(e2.seq), 0) + 1 FROM deployment_events e2 WHERE e2.deployment_id = ?),
    ?,
    ?
)
RETURNING seq
`

type InsertDeploymentEventParams struct {
	DeploymentID   int64
	DeploymentID_2 int64
	Type           string
	Message        string
}

func (q *Queries) InsertDeploymentEvent(ctx context.Context, arg InsertDeploymentEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertDeploymentEvent,
		arg.DeploymentID,
		arg.DeploymentID_2,
		arg.Type,
		arg.Message,
	)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const latestDeploymentID = `-- name: LatestDeploymentID :one
SELECT id FROM deployments WHERE project_id = ? ORDER BY number DESC LIMIT 1
`

func (q *Queries) LatestDeploymentID(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, latestDeploymentID, projectID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listDeploymentArtifacts = `-- name: ListDeploymentArtifacts :many
SELECT id, deployment_id, service, image_ref, image_digest FROM deployment_artifacts WHERE deployment_id = ? ORDER BY service
`

func (q *Queries) ListDeploymentArtifacts(ctx context.Context, deploymentID int64) ([]DeploymentArtifact, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentArtifacts, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentArtifact
	for rows.Next() {
		var i DeploymentArtifact
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Service,
			&i.ImageRef,
			&i.ImageDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentEvents = `-- name: ListDeploymentEvents :many
SELECT id, deployment_id, seq, ts, type, message FROM deployment_events
WHERE deployment_id = ? AND seq > ?
ORDER BY seq
LIMIT ?
`

type ListDeploymentEventsParams struct {
	DeploymentID int64
	Seq          int64
	Limit        int64
}

func (q *Queries) ListDeploymentEvents(ctx context.Context, arg ListDeploymentEventsParams) ([]DeploymentEvent, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentEvents, arg.DeploymentID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentEvent
	for rows.Next() {
		var i DeploymentEvent
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Seq,
			&i.Ts,
			&i.Type,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployments = `-- name: ListDeployments :many
SELECT d.id, d.project_id, d.number, d.status, d.triggered_by, d.git_commit, d.error, d.rollback_of, d.started_at, d.finished_at, d.created_at FROM deployments d
JOIN projects p ON p.id = d.project_id
WHERE p.name = ?
ORDER BY d.number DESC
LIMIT ?
`

type ListDeploymentsParams struct {
	Name  string
	Limit int64
}

func (q *Queries) ListDeployments(ctx context.Context, arg ListDeploymentsParams) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeployments, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Status,
			&i.TriggeredBy,
			&i.GitCommit,
			&i.Error,
			&i.RollbackOf,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeploymentStarted = `-- name: MarkDeploymentStarted :exec
UPDATE deployments
SET status = ?, started_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type MarkDeploymentStartedParams struct {
	Status string
	ID     int64
}

func (q *Queries) MarkDeploymentStarted(ctx context.Context, arg MarkDeploymentStartedParams) error {
	_, err := q.db.ExecContext(ctx, markDeploymentStarted, arg.Status, arg.ID)
	return err
}

const setDeploymentCommit = `-- name: SetDeploymentCommit :exec
UPDATE deployments SET git_commit = ? WHERE id = ?
`

type SetDeploymentCommitParams struct {
	GitCommit sql.NullString
	ID        int64
}

func (q *Queries) SetDeploymentCommit(ctx context.Context, arg SetDeploymentCommitParams) error {
	_, err := q.db.ExecContext(ctx, setDeploymentCommit, arg.GitCommit, arg.ID)
	return err
}

const setDeploymentStatus = `-- name: SetDeploymentStatus :exec
UPDATE deployments SET status = ? WHERE id = ?
`

type SetDeploymentStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) SetDeploymentStatus(ctx context.Context, arg SetDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, setDeploymentStatus, arg.Status, arg.ID)
	return err
}
