// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domains.sql

package db

import (
	"context"
)

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (project_id, hostname, service, container_port)
VALUES (?, ?, ?, ?)
RETURNING id, project_id, hostname, service, container_port, created_at
`

type CreateDomainParams struct {
	ProjectID     int64
	Hostname      string
	Service       string
	ContainerPort int64
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRowContext(ctx, createDomain,
		arg.ProjectID,
		arg.Hostname,
		arg.Service,
		arg.ContainerPort,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Hostname,
		&i.Service,
		&i.ContainerPort,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM domains WHERE id = ?
`

func (q *Queries) DeleteDomain(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDomain, id)
	return err
}

const getDomain = `-- name: GetDomain :one
SELECT d.id, d.project_id, d.hostname, d.service, d.container_port, d.created_at FROM domains d
JOIN projects p ON p.id = d.project_id
WHERE p.name = ? AND d.hostname = ?
`

type GetDomainParams struct {
	Name     string
	Hostname string
}

func (q *Queries) GetDomain(ctx context.Context, arg GetDomainParams) (Domain, error) {
	row := q.db.QueryRowContext(ctx, getDomain, arg.Name, arg.Hostname)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Hostname,
		&i.Service,
		&i.ContainerPort,
		&i.CreatedAt,
	)
	return i, err
}

const listAllDomains = `-- name: ListAllDomains :many
SELECT d.id, d.project_id, d.hostname, d.service, d.container_port, d.created_at, p.name AS project_name
FROM domains d
JOIN projects p ON p.id = d.project_id
ORDER BY d.hostname
`

type ListAllDomainsRow struct {
	ID            int64
	ProjectID     int64
	Hostname      string
	Service       string
	ContainerPort int64
	CreatedAt     string
	ProjectName   string
}

func (q *Queries) ListAllDomains(ctx context.Context) ([]ListAllDomainsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllDomainsRow
	for rows.Next() {
		var i ListAllDomainsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Hostname,
			&i.Service,
			&i.ContainerPort,
			&i.CreatedAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectDomains = `-- name: ListProjectDomains :many
SELECT id, project_id, hostname, service, container_port, created_at FROM domains WHERE project_id = ? ORDER BY hostname
`

func (q *Queries) ListProjectDomains(ctx context.Context, projectID int64) ([]Domain, error) {
	rows, err := q.db.QueryContext(ctx, listProjectDomains, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Hostname,
			&i.Service,
			&i.ContainerPort,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
