// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: env_vars.sql

package db

import (
	"context"
)

const deleteEnvVar = `-- name: DeleteEnvVar :exec
DELETE FROM env_vars WHERE project_id = ? AND key = ?
`

type DeleteEnvVarParams struct {
	ProjectID int64
	Key       string
}

func (q *Queries) DeleteEnvVar(ctx context.Context, arg DeleteEnvVarParams) error {
	_, err := q.db.ExecContext(ctx, deleteEnvVar, arg.ProjectID, arg.Key)
	return err
}

const deleteProjectEnvVars = `-- name: DeleteProjectEnvVars :exec
DELETE FROM env_vars WHERE project_id = ?
`

func (q *Queries) DeleteProjectEnvVars(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProjectEnvVars, projectID)
	return err
}

const listEnvVars = `-- name: ListEnvVars :many
SELECT id, project_id, "key", value_enc FROM env_vars WHERE project_id = ? ORDER BY key
`

func (q *Queries) ListEnvVars(ctx context.Context, projectID int64) ([]EnvVar, error) {
	rows, err := q.db.QueryContext(ctx, listEnvVars, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvVar
	for rows.Next() {
		var i EnvVar
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.ValueEnc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEnvVar = `-- name: UpsertEnvVar :exec
INSERT INTO env_vars (project_id, key, value_enc) VALUES (?, ?, ?)
ON CONFLICT(project_id, key) DO UPDATE SET value_enc = excluded.value_enc
`

type UpsertEnvVarParams struct {
	ProjectID int64
	Key       string
	ValueEnc  []byte
}

func (q *Queries) UpsertEnvVar(ctx context.Context, arg UpsertEnvVarParams) error {
	_, err := q.db.ExecContext(ctx, upsertEnvVar, arg.ProjectID, arg.Key, arg.ValueEnc)
	return err
}
