// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: git.sql

package db

import (
	"context"
	"database/sql"
)

const clearProjectGit = `-- name: ClearProjectGit :exec
UPDATE projects
SET source = 'manual', git_repo = NULL, git_branch = NULL, auto_deploy = 0,
    git_connection_id = NULL, webhook_secret_enc = NULL
WHERE id = ?
`

func (q *Queries) ClearProjectGit(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearProjectGit, id)
	return err
}

const configureProjectGit = `-- name: ConfigureProjectGit :exec
UPDATE projects
SET source = 'git', git_repo = ?, git_branch = ?, auto_deploy = ?,
    git_connection_id = ?, webhook_secret_enc = ?
WHERE id = ?
`

type ConfigureProjectGitParams struct {
	GitRepo          sql.NullString
	GitBranch        sql.NullString
	AutoDeploy       int64
	GitConnectionID  sql.NullInt64
	WebhookSecretEnc []byte
	ID               int64
}

func (q *Queries) ConfigureProjectGit(ctx context.Context, arg ConfigureProjectGitParams) error {
	_, err := q.db.ExecContext(ctx, configureProjectGit,
		arg.GitRepo,
		arg.GitBranch,
		arg.AutoDeploy,
		arg.GitConnectionID,
		arg.WebhookSecretEnc,
		arg.ID,
	)
	return err
}

const createGitConnection = `-- name: CreateGitConnection :one
INSERT INTO git_connections (provider, name, token_enc) VALUES (?, ?, ?)
RETURNING id, provider, name, token_enc, created_at
`

type CreateGitConnectionParams struct {
	Provider string
	Name     string
	TokenEnc []byte
}

func (q *Queries) CreateGitConnection(ctx context.Context, arg CreateGitConnectionParams) (GitConnection, error) {
	row := q.db.QueryRowContext(ctx, createGitConnection, arg.Provider, arg.Name, arg.TokenEnc)
	var i GitConnection
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Name,
		&i.TokenEnc,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGitConnection = `-- name: DeleteGitConnection :exec
DELETE FROM git_connections WHERE id = ?
`

func (q *Queries) DeleteGitConnection(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGitConnection, id)
	return err
}

const getGitConnection = `-- name: GetGitConnection :one
SELECT id, provider, name, token_enc, created_at FROM git_connections WHERE id = ?
`

func (q *Queries) GetGitConnection(ctx context.Context, id int64) (GitConnection, error) {
	row := q.db.QueryRowContext(ctx, getGitConnection, id)
	var i GitConnection
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Name,
		&i.TokenEnc,
		&i.CreatedAt,
	)
	return i, err
}

const listGitConnections = `-- name: ListGitConnections :many
SELECT id, provider, name, token_enc, created_at FROM git_connections ORDER BY name
`

func (q *Queries) ListGitConnections(ctx context.Context) ([]GitConnection, error) {
	rows, err := q.db.QueryContext(ctx, listGitConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitConnection
	for rows.Next() {
		var i GitConnection
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Name,
			&i.TokenEnc,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
