// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"
)

const checkpointJob = `-- name: CheckpointJob :exec
UPDATE jobs
SET step = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type CheckpointJobParams struct {
	Step string
	ID   int64
}

func (q *Queries) CheckpointJob(ctx context.Context, arg CheckpointJobParams) error {
	_, err := q.db.ExecContext(ctx, checkpointJob, arg.Step, arg.ID)
	return err
}

const claimNextJob = `-- name: ClaimNextJob :one
UPDATE jobs
SET status = 'running',
    attempts = attempts + 1,
    locked_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = (
    SELECT id FROM jobs
    WHERE status = 'queued' AND run_after <= strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
    ORDER BY id
    LIMIT 1
)
RETURNING id, type, payload, status, step, attempts, run_after, locked_at, created_at, updated_at
`

func (q *Queries) ClaimNextJob(ctx context.Context) (Job, error) {
	row := q.db.QueryRowContext(ctx, claimNextJob)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Step,
		&i.Attempts,
		&i.RunAfter,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO jobs (type, payload) VALUES (?, ?) RETURNING id, type, payload, status, step, attempts, run_after, locked_at, created_at, updated_at
`

type EnqueueJobParams struct {
	Type    string
	Payload string
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, enqueueJob, arg.Type, arg.Payload)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Step,
		&i.Attempts,
		&i.RunAfter,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishJob = `-- name: FinishJob :exec
UPDATE jobs
SET status = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type FinishJobParams struct {
	Status string
	ID     int64
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.ExecContext(ctx, finishJob, arg.Status, arg.ID)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, type, payload, status, step, attempts, run_after, locked_at, created_at, updated_at FROM jobs WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Step,
		&i.Attempts,
		&i.RunAfter,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reclaimRunningJobs = `-- name: ReclaimRunningJobs :execrows
UPDATE jobs
SET status = 'queued', updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE status = 'running'
`

func (q *Queries) ReclaimRunningJobs(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, reclaimRunningJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
