// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AuditLog struct {
	ID           int64
	Ts           string
	UserID       sql.NullInt64
	Action       string
	ResourceType sql.NullString
	ResourceID   sql.NullString
	Ip           sql.NullString
	Detail       sql.NullString
}

type EnvVar struct {
	ID        int64
	ProjectID int64
	Key       string
	ValueEnc  []byte
}

type Project struct {
	ID         int64
	Name       string
	Source     string
	GitRepo    sql.NullString
	GitBranch  sql.NullString
	AutoDeploy int64
	CreatedAt  string
}

type Session struct {
	ID        string
	UserID    int64
	CreatedAt string
	ExpiresAt string
	Ip        sql.NullString
	UserAgent sql.NullString
}

type Setting struct {
	Key   string
	Value string
}

type User struct {
	ID            int64
	Email         string
	PasswordHash  sql.NullString
	Role          string
	TotpSecretEnc []byte
	TotpEnabled   int64
	OauthProvider sql.NullString
	OauthSubject  sql.NullString
	CreatedAt     string
	DisabledAt    sql.NullString
}
