// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugins.sql

package db

import (
	"context"
)

const listEnabledPlugins = `-- name: ListEnabledPlugins :many
SELECT name FROM plugins WHERE enabled = 1
`

func (q *Queries) ListEnabledPlugins(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPluginEnabled = `-- name: SetPluginEnabled :exec
INSERT INTO plugins (name, enabled) VALUES (?, ?)
ON CONFLICT(name) DO UPDATE SET
    enabled = excluded.enabled,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

type SetPluginEnabledParams struct {
	Name    string
	Enabled int64
}

func (q *Queries) SetPluginEnabled(ctx context.Context, arg SetPluginEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setPluginEnabled, arg.Name, arg.Enabled)
	return err
}
