// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, source, git_repo, git_branch, auto_deploy)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, source, git_repo, git_branch, auto_deploy, created_at, git_connection_id, webhook_secret_enc
`

type CreateProjectParams struct {
	Name       string
	Source     string
	GitRepo    sql.NullString
	GitBranch  sql.NullString
	AutoDeploy int64
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.Name,
		arg.Source,
		arg.GitRepo,
		arg.GitBranch,
		arg.AutoDeploy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.GitRepo,
		&i.GitBranch,
		&i.AutoDeploy,
		&i.CreatedAt,
		&i.GitConnectionID,
		&i.WebhookSecretEnc,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, name, source, git_repo, git_branch, auto_deploy, created_at, git_connection_id, webhook_secret_enc FROM projects WHERE name = ?
`

func (q *Queries) GetProjectByName(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByName, name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.GitRepo,
		&i.GitBranch,
		&i.AutoDeploy,
		&i.CreatedAt,
		&i.GitConnectionID,
		&i.WebhookSecretEnc,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, source, git_repo, git_branch, auto_deploy, created_at, git_connection_id, webhook_secret_enc FROM projects ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Source,
			&i.GitRepo,
			&i.GitBranch,
			&i.AutoDeploy,
			&i.CreatedAt,
			&i.GitConnectionID,
			&i.WebhookSecretEnc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectGit = `-- name: UpdateProjectGit :exec
UPDATE projects SET git_repo = ?, git_branch = ?, auto_deploy = ? WHERE id = ?
`

type UpdateProjectGitParams struct {
	GitRepo    sql.NullString
	GitBranch  sql.NullString
	AutoDeploy int64
	ID         int64
}

func (q *Queries) UpdateProjectGit(ctx context.Context, arg UpdateProjectGitParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectGit,
		arg.GitRepo,
		arg.GitBranch,
		arg.AutoDeploy,
		arg.ID,
	)
	return err
}
