// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registries.sql

package db

import (
	"context"
)

const deleteRegistryCredential = `-- name: DeleteRegistryCredential :exec
DELETE FROM registry_credentials WHERE id = ?
`

func (q *Queries) DeleteRegistryCredential(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRegistryCredential, id)
	return err
}

const getRegistryCredential = `-- name: GetRegistryCredential :one
SELECT id, host, username, secret_enc, created_at, updated_at, verified_at FROM registry_credentials WHERE host = ?
`

func (q *Queries) GetRegistryCredential(ctx context.Context, host string) (RegistryCredential, error) {
	row := q.db.QueryRowContext(ctx, getRegistryCredential, host)
	var i RegistryCredential
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Username,
		&i.SecretEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const listRegistryCredentials = `-- name: ListRegistryCredentials :many
SELECT id, host, username, secret_enc, created_at, updated_at, verified_at FROM registry_credentials ORDER BY host
`

func (q *Queries) ListRegistryCredentials(ctx context.Context) ([]RegistryCredential, error) {
	rows, err := q.db.QueryContext(ctx, listRegistryCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistryCredential
	for rows.Next() {
		var i RegistryCredential
		if err := rows.Scan(
			&i.ID,
			&i.Host,
			&i.Username,
			&i.SecretEnc,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRegistryVerified = `-- name: MarkRegistryVerified :exec
UPDATE registry_credentials
   SET verified_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
 WHERE host = ?
`

func (q *Queries) MarkRegistryVerified(ctx context.Context, host string) error {
	_, err := q.db.ExecContext(ctx, markRegistryVerified, host)
	return err
}

const upsertRegistryCredential = `-- name: UpsertRegistryCredential :one
INSERT INTO registry_credentials (host, username, secret_enc, updated_at)
VALUES (?, ?, ?, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
ON CONFLICT(host) DO UPDATE SET
    username   = excluded.username,
    secret_enc = excluded.secret_enc,
    updated_at = excluded.updated_at
RETURNING id, host, username, secret_enc, created_at, updated_at, verified_at
`

type UpsertRegistryCredentialParams struct {
	Host      string
	Username  string
	SecretEnc []byte
}

func (q *Queries) UpsertRegistryCredential(ctx context.Context, arg UpsertRegistryCredentialParams) (RegistryCredential, error) {
	row := q.db.QueryRowContext(ctx, upsertRegistryCredential, arg.Host, arg.Username, arg.SecretEnc)
	var i RegistryCredential
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Username,
		&i.SecretEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedAt,
	)
	return i, err
}
